name: ci

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.rst'
  push:
    paths-ignore:
    - '**.md'
    - '**.rst'
    branches-ignore:
    - 'master'
    - 'melpazoidberg'
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [27.1]
        python_version: [3.6]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/cache@v2
      with:
        path: ~/local
        key: local-002

    - uses: actions/cache@v2
      with:
        path: ~/.emacs.d
        key: emacs.d-002

    - uses: actions/cache@v2
      with:
        path: ~/.cask
        key: cask-002

    - name: Paths
      run: |
        echo "$HOME/local/bin" >> $GITHUB_PATH
        echo "$HOME/local/cask/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get -yq update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install git jq mercurial texinfo

        # Work around SSL-related failures, see
        # https://stackoverflow.com/questions/21477683/mercurial-https-clone-abort-error-wrong-version-number
        echo "[ui]\ntls = False" > $HOME/.hgrc

    - name: Install cask
      run: |
        sh scripts/install-cask.sh
        cask link list

    - name: Check changed recipes
      run: |
        [ "$GITHUB_EVENT_NAME" = "push" ] \
          && export CHANGED_FILES=$(git diff-tree --name-only --no-commit-id -r ${{ github.sha }})

        [ "$GITHUB_EVENT_NAME" = "pull_request" ] \
          && set -eo pipefail \
          && export CHANGED_FILES=$(curl -sSL ${{ github.event.pull_request.url }}/files | jq -r ".[] | .filename")

        ./run-ci.sh

    - uses: actions/upload-artifact@v2
      with:
        name: mz.artifact
        path: /var/tmp/mz.artifact
