name: lint

# Adapted: securitylab.github.com/research/github-actions-preventing-pwn-requests

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  respond:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            if (artifacts.data.total_count != 0) {
              var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "mz.artifact"
              })[0];
              if (matchArtifact) {
                var download = await github.actions.downloadArtifact({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   artifact_id: matchArtifact.id,
                   archive_format: 'zip',
                });
                var fs = require('fs');
                fs.writeFileSync('${{github.workspace}}/mz.artifact.zip', Buffer.from(download.data));
              }
            }

      - run: unzip mz.artifact.zip
        if: hashFiles('mz.artifact.zip') != ''

      - name: 'Robo-respond to PR'
        if: hashFiles('mz.number') != ''
        uses: actions/github-script@v3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var number = Number(fs.readFileSync('./mz.number', 'utf8'));
            var body = fs.readFileSync('./mz.out', 'utf8');
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: body,
            });
